### PR TITLE
Serialize enum metadata

### LINKED ISSUE #198: Passing enums as metadata values breaks the reporting
### Description

When there is an enum value among the metadata values, an error is thrown pointing to stringifying the metadata. This happens with both the `.leaveBreadcrumb()` and `.notify()` methods. 

### Steps to reproduce

I'm sending an [`OperationType` object](https://pub.dev/documentation/gql/latest/ast/OperationType.html) as a metadata value in my workflow. Underneath, the library struggles with stringifying it.  It's a simple enum, but it breaks logging and error reporting!
I was able to reproduce this with any enum.
As a workaround, currently, I always convert my enum to a string before passing it in.

### Environment

- Bugsnag version: 2.4.0
- Flutter version: 3.7.10
- Flutter-first app or native app with Flutter component(s): Flutter-first
- iOS/Android version: iOS 14
- Simulator/emulator or physical device: Simulator

### Code example:
```dart
enum TestEnum {
  value1,
  value2,
  value3,
}

    bugsnag.leaveBreadcrumb(
      'message',
      metadata: {'enum': TestEnum.value1},
      type: BugsnagBreadcrumbType.request,
    );
```

### Error message:
```
flutter: error: Converting object to an encodable object failed: Instance of 'BugsnagBreadcrumb'
flutter: stackTrace: #0      _JsonStringifier.writeObject (dart:convert/json.dart:793:7)
#1      _JsonStringifier.writeMap (dart:convert/json.dart:874:7)
#2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:829:21)
#3      _JsonStringifier.writeObject (dart:convert/json.dart:784:9)
#4      _JsonStringStringifier.printOn (dart:convert/json.dart:982:17)
#5      _JsonStringStringifier.stringify (dart:convert/json.dart:967:5)
#6      JsonEncoder.convert (dart:convert/json.dart:345:30)
#7      JsonCodec.encode (dart:convert/json.dart:231:45)
#8      JSONMessageCodec.encodeMessage
message_codecs.dart:103
#9      JSONMethodCodec.encodeMethodCall
message_codecs.dart:139
#10     MethodChannel._invokeMethod
platform_channel.dart:304
#11     MethodChannel.invokeMethod
platform_channel.dart:491
#12     ChannelClient.leaveBreadcrumb (package:bugsnag_flutter/src/c<…>
```

### PR DESCRIPTION
**Pull request by 0HyperCube**
## Goal

Closes #198

## Design

The metadata is now always sanitised, meaning that all enums are converted to strings.

## Testing

Test added to ensure that different data types are properly sanitised when passed as metadata.

### CODE REVIEW

File: packages/bugsnag_flutter/lib/src/model/breadcrumbs.dart [hunk 1]
```diff
@@ -9,11 +9,10 @@ class BugsnagBreadcrumb {
...
 
-  BugsnagBreadcrumb(
-    this.message, {
-    this.type = BugsnagBreadcrumbType.manual,
-    this.metadata,
-  }) : timestamp = DateTime.now().toUtc();
+  BugsnagBreadcrumb(this.message,
+      {this.type = BugsnagBreadcrumbType.manual, Map<String, Object>? metadata})
+      : timestamp = DateTime.now().toUtc(),
+        metadata = BugsnagMetadata.sanitizedMap(metadata ?? {});
```
Comment (lemnik) [inline packages/bugsnag_flutter/lib/src/model/breadcrumbs.dart:15]: We should probably be sanitizing the data in `toJson()`. This avoids unexpectedly changing the visible content of `metadata` (a public API). It would also move the performance impact later in the breadcrumb lifecycle (ie: we only sanitize the data if it is converted to JSON), which is advantageous since ultimately most breadcrumbs are discarded.

File: packages/bugsnag_flutter/test/channel_client_test.dart [hunk 2]
```diff
@@ -124,6 +125,37 @@ void main() {
...
+          "Map": Map<String, Object>.from({"1": 2}),
+        };
+        final breadcrumb = BugsnagBreadcrumb("Hello",
+            type: BugsnagBreadcrumbType.manual, metadata: sampleMetadata);
+
+        expect(breadcrumb.metadata?["List"], equals([1, 2, 3]));
+        expect(breadcrumb.metadata?["Enum"],
+            equals("BugsnagBreadcrumbType.manual"));
+        expect(breadcrumb.metadata?["Map"], equals({"1": 2}));
+      });
```
Comment (lemnik) [inline packages/bugsnag_flutter/test/channel_client_test.dart:158]: It would be good to see these tests run through a full Object -> Json -> Object cycle, which would also catch any future breaks in that contract.

**Review by lemnik — APPROVED** [review]
LGTM - Pending a CHANGELOG entry
